### ISSUE TITLE
Crash rendering Create UI on android

### ISSUE THREAD

**Issue by SCOS100** [Engine-Room/Flywheel#182]
So i was trying to get create and flywheel installed, but it just won't even start. Any Solutions?

**Comment by Jozufozu** [comment]
Need the full log to be able to say anything at all. "Not Initialized" just means the game crashed before Flywheel had a chance to decide what backend to use.

**Comment by SCOS100** [comment]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2023-05-19 21:25:21
Description: Unexpected error

java.lang.RuntimeException: GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83949_(RenderTarget.java:161) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83950_(RenderTarget.java:139) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83964_(RenderTarget.java:63) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83941_(RenderTarget.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.enableStencil(RenderTarget.java:316) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.simibubi.create.foundation.gui.UIRenderHelper$CustomRenderTarget.create(UIRenderHelper.java:288) ~[create-1.19.2-0.5.0.i.jar%23132!/:0.5.0.i] {re:classloading}
	at com.simibubi.create.foundation.gui.UIRenderHelper.lambda$init$0(UIRenderHelper.java:38) ~[create-1.19.2-0.5.0.i.jar%23132!/:0.5.0.i] {re:mixin,re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.m_69884_(RenderSystem.java:211) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.mixins.json:RenderTexturesMixin,pl:mixin:A}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:198) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.mixins.json:RenderTexturesMixin,pl:mixin:A}
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:337) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1143) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.11.jar%2359!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83949_(RenderTarget.java:161) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83950_(RenderTarget.java:139) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83964_(RenderTarget.java:63) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83941_(RenderTarget.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.enableStencil(RenderTarget.java:316) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.simibubi.create.foundation.gui.UIRenderHelper$CustomRenderTarget.create(UIRenderHelper.java:288) ~[create-1.19.2-0.5.0.i.jar%23132!/:0.5.0.i] {re:classloading}
	at com.simibubi.create.foundation.gui.UIRenderHelper.lambda$init$0(UIRenderHelper.java:38) ~[create-1.19.2-0.5.0.i.jar%23132!/:0.5.0.i] {re:mixin,re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.m_69884_(RenderSystem.java:211) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.mixins.json:RenderTexturesMixin,pl:mixin:A}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:198) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.mixins.json:RenderTexturesMixin,pl:mixin:A}
-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Mod Resources, Default
Stacktrace:
	at net.minecraft.client.ResourceLoadStateTracker.m_168562_(ResourceLoadStateTracker.java:49) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2287) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:722) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23143!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.11.jar%2359!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (aarch64) version Android-8.0.0
	Java Version: 17.0.7-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 654757064 bytes (624 MiB) / 1855979520 bytes (1770 MiB) up to 1855979520 bytes (1770 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: 
	Identifier: 0x41 Family 8 Model 0xd03 Stepping r0x0p4
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 4134.10
	Virtual memory used (MB): 4118.00
	Swap memory total (MB): 2240.00
	Swap memory used (MB): 618.59
	JVM Flags: 3 total; -Xms1770M -Xmx1770M -Xbootclasspath/a:/storage/emulated/0/games/PojavLauncher/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	Window size: 2160x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x 
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.2.11.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.11.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.2.11.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.2.11.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.11.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |ENQUEUE_IM|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		create_misc_and_things_1.19.2_2.0.jar             |create: things and misc       |create_things_and_misc        |1.0.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		forge-1.19.2-43.2.11-universal.jar                |Forge                         |forge                         |43.2.11             |ENQUEUE_IM|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		flywheel-forge-1.19.2-0.6.8.a.jar                 |Flywheel                      |flywheel                      |0.6.8.a             |ENQUEUE_IM|Manifest: NOSIGNATURE
		create-1.19.2-0.5.0.i.jar                         |Create                        |create                        |0.5.0.i             |ENQUEUE_IM|Manifest: NOSIGNATURE
		extendedgears-2.0.2-1.19.2-0.5.0.iforge-1.19.2.jar|Extended Cogwheels            |extendedgears                 |2.0.2-1.19.2-0.5.0.i|ENQUEUE_IM|Manifest: NOSIGNATURE
		CreateCasing-1.19.2-1.1.2-hotfix-2.jar            |Create : Encased              |createcasing                  |1.19.2-1.1.2-hotfix-|ENQUEUE_IM|Manifest: NOSIGNATURE
		create_dragon_lib-1.19.2-1.1.2.jar                |Create: Dragon Lib            |create_dragon_lib             |1.1.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		create_enchantment_industry-1.19.2-for-create-0.5.|Create Enchantment Industry   |create_enchantment_industry   |1.2.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		Steam_Rails-1.2.6+forge-mc1.19.2.jar              |Create: Steam 'n Rails        |railways                      |1.2.6+forge-mc1.19.2|ENQUEUE_IM|Manifest: NOSIGNATURE
		nocube's_create_compact_exp_1.0.1_forge_1.19.2.jar|Create Compact Exp (by NoCube)|nocubescreateexp              |1.0.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.6.0.1015.jar                  |Just Enough Items             |jei                           |11.6.0.1015         |ENQUEUE_IM|Manifest: NOSIGNATURE
	****Flywheel Backend: Uninitialized****
	Crash Report UUID: 272d9127-bf64-4535-b9a2-ae776c1dbebf
	FML: 43.2
	Forge: net.minecraftforge:43.2.11

**Comment by Jozufozu** [comment]
Looks like the crash is with Create's UI rendering logic running into some issue with the opengl adapter. First time I've seen this, but not a flywheel issue.
