### ISSUE TITLE
ArrayIndexOutOfBounds: 16 crash

### ISSUE THREAD

**Issue by Partonetrain** [Engine-Room/Flywheel#2]
Hi, we're using a prerelease version of Create (because of https://github.com/Creators-of-Create/Create/issues/1799), which requires Flywheel. I crash within minutes of joining my server, and it looks like Flywheel's LightUpdateMixin is the issue. 

```
java.lang.ArrayIndexOutOfBoundsException: 16
	at net.minecraft.client.multiplayer.ClientChunkProvider.handler$bfe000$onLightUpdate(ClientChunkProvider.java:551) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:light.LightUpdateMixin,pl:mixin:APP:mixins.betterf3.json:chunk.ClientChunkProviderAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.ClientChunkProvider.func_217201_a(ClientChunkProvider.java) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:light.LightUpdateMixin,pl:mixin:APP:mixins.betterf3.json:chunk.ClientChunkProviderAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.lighting.SectionLightStorage.func_215533_d(SourceFile:388) ~[?:?] {re:classloading}
	at net.minecraft.world.lighting.LightEngine.func_215616_a(LightEngine.java:170) ~[?:?] {re:classloading}
	at net.minecraft.world.lighting.WorldLightManager.func_215575_a(SourceFile:61) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:899) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?] {re:classloading,xf:fml:screenshotclipboard:coremodone,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.32.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
```

I did try this without BetterF3 and got the same crash. Disabling the Flywheel "engine" in the config did not help. I was not able to get this crash in singleplayer.

Full Log: https://pastebin.com/Eng6Hgmf

Thanks in advance!

**Comment by Jozufozu** [comment]
Thanks for the report! You can download a jar with the fix [here](https://ci.tterrag.com/job/Flywheel/job/Forge/job/1.16/).
