### ISSUE TITLE
Not showing download

### ISSUE THREAD

**Issue by StrawberryPlague** [Engine-Room/Flywheel#208]
### Describe the Bug

There is no 1.20.1 version on feather client and is not showing any version to download. 

### Reproduction Steps

1.
2.
3.
...
Idk what to put sorry

### Expected Result

Be able to download flywheel 1.20.1 on featherclient

### Screenshots and Videos

<img width="924" alt="image" src="https://github.com/Jozufozu/Flywheel/assets/149195689/32849382-6d92-4816-8f5b-9d14578838af">

### Crash Report or Log

Incompatible mods found! net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other! A potential solution has been determined, this may resolve your problem: 	 - Replace mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 with any version that is compatible with: 		 - sodium 0.5.3 More details: 	 - Mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 is incompatible with version 0.5.0 or later of mod 'Sodium' (sodium), but a matching version is present: 0.5.3! 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) 	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:194) 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) 	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)

### Operating System

Windows 11

### What is your GPU?

AMD Ryzen 5 5625U

### Mod Version

0.6.10

### Minecraft Version

1.20.1

### Loader Version

Fabric 1.201

### Other Mods

nothing to say

### Additional Context

nothing to say

**Comment by sa1672ndo** [comment]
"Mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 is incompatible with version 0.5.0 or later of mod 'Sodium' (sodium), but a matching version is present: 0.5.3"
1st: sodium 0.5.3 is not compatible with create, you should remove it.
2nd: create 0.5.1-d comes with flywheel , you don't have to download it separately.
