### ISSUE TITLE
flywheel has failed to load correctly

### ISSUE THREAD

**Issue by Cancer-41424** [Engine-Room/Flywheel#271]
### Describe the Bug

I only add create to play minecraft but it tell me flywheel has failed to load correctly

### Reproduction Steps

1.add create
2.
3.
...

### Expected Result

I want to know how to play this mod

### Screenshots and Videos

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-11-11 20:03:49
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.1.39-universal.jar%23163!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:143) ~[forge-1.20.1-47.1.39-universal.jar%23163!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:146) ~[forge-1.20.1-47.1.39-universal.jar%23163!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[最小的机械动力.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.39.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.39.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.39.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?] {}
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:110) ~[?:?] {}
	at oolloo.jlw.Wrapper.main(Wrapper.java:103) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.jozufozu.flywheel.backend.instancing.InstancedRenderRegistry.setController(InstancedRenderRegistry.java:158) ~[flywheel-forge-1.20-0.6.9-4.jar%23167!/:0.6.9-4] {re:classloading}
-- MOD flywheel --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.1.39.jar%23160!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.1.39.jar%23159!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /D:/PCL~~~~/.minecraft/versions/最小的机械动力/mods/create-1.20.1-0.5.1.d.jar#157!/META-INF/jarjar/flywheel-forge-1.20-0.6.9-4.jar
	Failure message: Flywheel (flywheel) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 0.6.9-4
	Mod Issue URL: https://github.com/Jozufozu/Flywheel/issues
	Exception message: java.lang.ClassCastException: class net.minecraft.world.level.block.entity.BlockEntityType cannot be cast to class com.jozufozu.flywheel.backend.instancing.blockentity.BlockEntityTypeExtension (net.minecraft.world.level.block.entity.BlockEntityType is in module minecraft@1.20.1 of loader 'TRANSFORMER' @6a0f2853; com.jozufozu.flywheel.backend.instancing.blockentity.BlockEntityTypeExtension is in module flywheel@0.6.9-4 of loader 'TRANSFORMER' @6a0f2853)
Stacktrace:
	at com.jozufozu.flywheel.backend.instancing.InstancedRenderRegistry.setController(InstancedRenderRegistry.java:158) ~[flywheel-forge-1.20-0.6.9-4.jar%23167!/:0.6.9-4] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstancedRenderRegistry$BlockEntityConfig.apply(InstancedRenderRegistry.java:243) ~[flywheel-forge-1.20-0.6.9-4.jar%23167!/:0.6.9-4] {re:classloading}
	at com.jozufozu.flywheel.vanilla.VanillaInstances.init(VanillaInstances.java:34) ~[flywheel-forge-1.20-0.6.9-4.jar%23167!/:0.6.9-4] {re:classloading}
	at com.jozufozu.flywheel.Flywheel.clientInit(Flywheel.java:80) ~[flywheel-forge-1.20-0.6.9-4.jar%23167!/:0.6.9-4] {re:classloading}
	at com.jozufozu.flywheel.Flywheel.lambda$new$3(Flywheel.java:63) ~[flywheel-forge-1.20-0.6.9-4.jar%23167!/:0.6.9-4] {re:classloading}
	at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111) ~[fmlcore-1.20.1-47.1.39.jar%23159!/:?] {}
	at com.jozufozu.flywheel.Flywheel.<init>(Flywheel.java:63) ~[flywheel-forge-1.20-0.6.9-4.jar%23167!/:0.6.9-4] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.1.39.jar%23160!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.1.39.jar%23159!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.12, BellSoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), BellSoft
	Memory: 472061224 bytes (450 MiB) / 843055104 bytes (804 MiB) up to 5582618624 bytes (5324 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 8845H w/ Radeon 780M Graphics
	Identifier: AuthenticAMD Family 25 Model 117 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon 780M Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x1900
	Graphics card #0 versionInfo: DriverVersion=31.0.22032.1
	Graphics card #1 name: NVIDIA GeForce RTX 4060 Laptop GPU
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x28a0
	Graphics card #1 versionInfo: DriverVersion=32.0.15.6109
	Memory slot #0 capacity (MB): 12288.00
	Memory slot #0 clockSpeed (GHz): 5.60
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 12288.00
	Memory slot #1 clockSpeed (GHz): 5.60
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 25389.35
	Virtual memory used (MB): 21683.41
	Swap memory total (MB): 1536.00
	Swap memory used (MB): 63.73
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn798m -Xmx5324m
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.1.39.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.39.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.1.39.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.1.39.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.39.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.20.1-47.1.39-universal.jar                |Forge                         |forge                         |47.1.39             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		flywheel-forge-1.20-0.6.9-4.jar                   |Flywheel                      |flywheel                      |0.6.9-4             |ERROR     |Manifest: NOSIGNATURE
		create-1.20.1-0.5.1.d.jar                         |Create                        |create                        |0.5.1.d             |COMMON_SET|Manifest: NOSIGNATURE
	Flywheel Backend: GL33 Instanced Arrays
	Crash Report UUID: 3486309f-f6c1-4fd9-ab36-c4594dd56d7b
	FML: 47.1
	Forge: net.minecraftforge:47.1.39

### Operating System

windows11

### What is your GPU?

rtx4060

### Mod Version

0.6.8.a

### Minecraft Version

1.19.2

### Loader Version

forge47.1.39

**Comment by Cancer-41424** [comment]
my minecraft version is 1.20.1

**Comment by Plite7067** [comment]
If you have flywheel in your mods, remove it, otherwise, upload your latest.log **as a file**

**Comment by Plite7067** [comment]
Can you upload your file to https://mclo.gs/ and send the link here?

**Comment by Cancer-41424** [comment]
https://mclo.gs/nFICYLh

**Comment by Cancer-41424** [comment]
sorry, i  don't know how to use github.  i  am a newcomer.

**Comment by Cancer-41424** [comment]
> 您能否将文件上传到 https://mclo.gs/ 并将链接发送到此处？

https://mclo.gs/nFICYLh

**Comment by Plite7067** [comment]
The mod needs to be in a file path without any ~, see this issue: https://github.com/Engine-Room/Flywheel/issues/258

**Comment by Cancer-41424** [comment]
> The mod needs to be in a file path without any ~, see this issue: #258

oh my god ! you are my Elegant！I spent one day try to solve this problem！ 3Q3Q
