### ISSUE TITLE
java.lang.NullPointerException: Unexpected error

### ISSUE THREAD

**Issue by aylacullen** [Engine-Room/Flywheel#35]
One of the players on my server visited another player whom was running a couple contraptions with the CreateMod.  That player's client crashed out after entering that player's base via the portal from the nether side to the overworld side (where the base is located).  Restarting client and PC makes no difference, it keeps crashing.  Logs indicate that a CreateMod contraption is causing problems with Flywheel, resulting in Flywheel crashing the client. 

Here's logs. 

`---- Minecraft Crash Report ----
// Why did you do that?

Time: 8/21/21 9:54 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.jozufozu.flywheel.backend.model.ModelRenderer.draw(ModelRenderer.java:24) ~[?:1.16-0.2.0] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.RenderedContraption.doRenderLayer(RenderedContraption.java:70) ~[?:mc1.16.5_v0.3.2c] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraptionManager.renderLayer(FlwContraptionManager.java:55) ~[?:mc1.16.5_v0.3.2c] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderDispatcher.renderLayer(ContraptionRenderDispatcher.java:62) ~[?:mc1.16.5_v0.3.2c] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_203_ContraptionRenderDispatcher_renderLayer_RenderLayerEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraft.client.renderer.WorldRenderer.handler$zze000$renderLayer(WorldRenderer.java:3719) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.markForRerender,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228441_a_(WorldRenderer.java:1263) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.markForRerender,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:956) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.markForRerender,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.2.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.0.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.jozufozu.flywheel.backend.model.ModelRenderer.draw(ModelRenderer.java:24) ~[?:1.16-0.2.0] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.RenderedContraption.doRenderLayer(RenderedContraption.java:70) ~[?:mc1.16.5_v0.3.2c] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraptionManager.renderLayer(FlwContraptionManager.java:55) ~[?:mc1.16.5_v0.3.2c] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderDispatcher.renderLayer(ContraptionRenderDispatcher.java:62) ~[?:mc1.16.5_v0.3.2c] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_203_ContraptionRenderDispatcher_renderLayer_RenderLayerEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraft.client.renderer.WorldRenderer.handler$zze000$renderLayer(WorldRenderer.java:3719) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.markForRerender,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228441_a_(WorldRenderer.java:1263) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.markForRerender,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:956) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.markForRerender,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 2 total; [ClientPlayerEntity['nise7en'/841000, l='ClientLevel', x=-1433.26, y=72.00, z=1157.50], RemoteClientPlayerEntity['VsXRaixeN'/801568, l='ClientLevel', x=-1409.70, y=50.00, z=1166.30]]
	Chunk stats: Client Chunk Cache: 729, 578
	Level dimension: minecraft:overworld
	Level spawn location: World: (-30,63,4), Chunk: (at 2,3,4 in -2,0; contains blocks -32,0,0 to -17,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 16761115 game time, 23746896 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.2.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.0.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Mac OS X (x86_64) version 10.15.7
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 11286796720 bytes (10763 MB) / 13019119616 bytes (12416 MB) up to 17179869184 bytes (16384 MB)
	CPUs: 4
	JVM Flags: 9 total; -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.0
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		CraftTweaker-1.16.5-7.1.0.369.jar                 |CraftTweaker                  |crafttweaker                  |7.1.0.369           |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.0-universal.jar                 |Forge                         |forge                         |36.2.0              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		flywheel-1.16-0.2.0.jar                           |Flywheel                      |flywheel                      |1.16-0.2.0          |DONE      |Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2c.jar                       |Create                        |create                        |v0.3.2c for 1.16.5  |DONE      |Manifest: NOSIGNATURE
		architectury-1.20.28-forge.jar                    |Architectury                  |architectury                  |1.20.28             |DONE      |Manifest: NOSIGNATURE
		ftb-library-forge-1605.3.1-build.56.jar           |FTB Library                   |ftblibrary                    |1605.3.1-build.56   |DONE      |Manifest: NOSIGNATURE
		journeymap-1.16.5-5.7.3.jar                       |Journeymap                    |journeymap                    |5.7.3               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.116.jar                          |Just Enough Items             |jei                           |7.7.1.116           |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 4d309c7d-5b49-49e0-aabb-8b5222da247a
	Launched Version: 1.16.5-forge-36.2.0
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: NVIDIA GeForce GTX 780M OpenGL Engine GL version 2.1 NVIDIA-14.0.32 355.11.11.10.10.143, NVIDIA Corporation
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	GPU Warnings: version: 2.1
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz`

**Comment by aylacullen** [comment]
Note: I have advised player to upgrade to 0.2.3 as I noted he was running 0.2.0.  I will update here once he does so.

**Comment by aylacullen** [comment]
Still crashing with the same error even with 0.2.3.

**Comment by Jozufozu** [comment]
Updating Create to 0.3.2d should fix the crash

**Comment by aylacullen** [comment]
Confirming that updating Create to 0.3.2d resolved issue.  Thanks!
