### ISSUE TITLE
Crash with Flywheel

### ISSUE THREAD

**Issue by StrangerSon71** [Engine-Room/Flywheel#4]
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 7/10/21 4:42 PM
Description: Rendering overlay

com.jozufozu.flywheel.backend.loading.ShaderLoadingException: Could not load all shaders, see log for details
	at com.jozufozu.flywheel.backend.ShaderSources.onResourceManagerReload(ShaderSources.java:92) ~[?:1.16-0.1.0] {re:classloading}
	at net.minecraftforge.resource.ISelectiveResourceReloadListener.func_195410_a(ISelectiveResourceReloadListener.java:33) ~[?:?] {re:classloading}
	at net.minecraft.resources.IResourceManagerReloadListener.func_232635_a_(IResourceManagerReloadListener.java:18) ~[?:?] {re:classloading,re:mixin}
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) ~[?:1.8.0_74] {}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) ~[?:1.8.0_74] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_74] {}
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.0.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.jozufozu.flywheel.backend.ShaderSources.onResourceManagerReload(ShaderSources.java:92) ~[?:1.16-0.1.0] {re:classloading}
	at net.minecraftforge.resource.ISelectiveResourceReloadListener.func_195410_a(ISelectiveResourceReloadListener.java:33) ~[?:?] {re:classloading}
	at net.minecraft.resources.IResourceManagerReloadListener.func_232635_a_(IResourceManagerReloadListener.java:18) ~[?:?] {re:classloading,re:mixin}
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) ~[?:1.8.0_74] {}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) ~[?:1.8.0_74] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_74] {}
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:484) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.0.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Mac OS X (x86_64) version 10.14.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1117158856 bytes (1065 MB) / 1985478656 bytes (1893 MB) up to 4056416256 bytes (3868 MB)
	CPUs: 8
	JVM Flags: 4 total; -Xss1M -Xmx4352m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.0
	FML Language Providers: 
		javafml@36.1
		minecraft@1
		kotlinforforge@1.13.0
	Mod List: 
		QuarkOddities-1.16.3.jar                          |Quark Oddities                |quarkoddities                 |1.16.3              |ENQUEUE_IM|NOSIGNATURE
		mowziesmobs-1.5.19.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.19              |ENQUEUE_IM|NOSIGNATURE
		dusk-1.4.jar                                      |Example Mod                   |dusk                          |1.4                 |ENQUEUE_IM|NOSIGNATURE
		infernal-expansion-forge-1.3.jar                  |Infernal Expansion            |infernalexp                   |Release 1.3         |ENQUEUE_IM|NOSIGNATURE
		MoreJellyfish-1.1.5.jar                           |More Jellyfish                |more_jellyfish                |1.0.0               |ENQUEUE_IM|NOSIGNATURE
		jei-1.16.5-7.7.0.106.jar                          |Just Enough Items             |jei                           |7.7.0.106           |ENQUEUE_IM|NOSIGNATURE
		abnormals_core-1.16.5-3.2.0.jar                   |Abnormals Core                |abnormals_core                |3.2.0               |ENQUEUE_IM|NOSIGNATURE
		buzzier_bees-1.16.5-3.0.1.jar                     |Buzzier Bees                  |buzzier_bees                  |3.0.1               |ENQUEUE_IM|NOSIGNATURE
		berry_good-1.16.5-4.1.1.jar                       |Berry Good                    |berry_good                    |4.1.1               |ENQUEUE_IM|NOSIGNATURE
		Fruitful-1.16.5-2.1.0.jar                         |Fruitful                      |fruitful                      |1.16.5-2.1.0        |ENQUEUE_IM|NOSIGNATURE
		cookielicious-1.16.5-1.2.2.jar                    |Cookielicious                 |cookielicious                 |1.2.2               |ENQUEUE_IM|NOSIGNATURE
		Enhanced-Mushrooms-1.16.5-3.0.9.jar               |Enhanced Mushrooms            |enhanced_mushrooms            |1.16.5-3.0.9        |ENQUEUE_IM|NOSIGNATURE
		Jellyfishing-1.6.9.jar                            |Jellyfishing                  |jellyfishing                  |1.6.8               |ENQUEUE_IM|NOSIGNATURE
		caelus-forge-1.16.5-2.1.3.0.jar                   |Caelus API                    |caelus                        |1.16.5-2.1.3.0      |ENQUEUE_IM|NOSIGNATURE
		Better-Badlands-1.16.5-2.0.3.jar                  |Better Badlands               |better_badlands               |1.16.5-2.0.3        |ENQUEUE_IM|NOSIGNATURE
		extraboats-1.16.5-2.1.0.jar                       |Extra Boats                   |extraboats                    |2.1.0               |ENQUEUE_IM|NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        |ENQUEUE_IM|NOSIGNATURE
		shutupexperimentalsettings-1.0.3.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.3               |ENQUEUE_IM|NOSIGNATURE
		mgui-1.16.5-3.2.0.jar                             |mgui                          |mgui                          |3.2.0               |ENQUEUE_IM|NOSIGNATURE
		Controlling-7.0.0.23.jar                          |Controlling                   |controlling                   |7.0.0.23            |ENQUEUE_IM|NOSIGNATURE
		Placebo-1.16.4-4.5.0.jar                          |Placebo                       |placebo                       |4.5.0               |ENQUEUE_IM|NOSIGNATURE
		comforts-forge-1.16.5-4.0.1.1.jar                 |Comforts                      |comforts                      |1.16.5-4.0.1.1      |ENQUEUE_IM|NOSIGNATURE
		citadel-1.7.1-1.16.5.jar                          |Citadel                       |citadel                       |1.7.1               |ENQUEUE_IM|NOSIGNATURE
		alexsmobs-1.11.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.11.1              |ENQUEUE_IM|NOSIGNATURE
		Artifacts-1.16.5-2.10.0.jar                       |Artifacts                     |artifacts                     |1.16.5-2.10.0       |ENQUEUE_IM|NOSIGNATURE
		YungsApi-1.16.4-Forge-6.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-6      |ENQUEUE_IM|NOSIGNATURE
		OuterEnd-0.2.13.jar                               |The Outer End                 |outer_end                     |0.2.9               |ENQUEUE_IM|NOSIGNATURE
		environmental-1.16.5-1.0.0.jar                    |Environmental                 |environmental                 |1.0.0               |ENQUEUE_IM|NOSIGNATURE
		Bayou-Blues-1.16.5-1.0.5.jar                      |Bayou Blues                   |bayou_blues                   |1.16.5-1.0.5        |ENQUEUE_IM|NOSIGNATURE
		champions-forge-1.16.5-2.0.1.7.jar                |Champions                     |champions                     |1.16.5-2.0.1.7      |ENQUEUE_IM|NOSIGNATURE
		curioofundying-forge-1.16.5-5.2.0.0.jar           |Curio of Undying              |curioofundying                |1.16.5-5.2.0.0      |ENQUEUE_IM|NOSIGNATURE
		iceandfire-2.1.8-1.16.5.jar                       |Ice and Fire                  |iceandfire                    |2.1.8-1.16.5        |ENQUEUE_IM|NOSIGNATURE
		Toast-Control-1.16.4-4.3.1.jar                    |Toast Control                 |toastcontrol                  |4.3.1               |ENQUEUE_IM|NOSIGNATURE
		JEITweaker-1.16.5-1.0.1.33.jar                    |JEI Tweaker                   |jeitweaker                    |1.0.1.33            |ENQUEUE_IM|NOSIGNATURE
		mystical_pumpkins-0.3.0.jar                       |Mystical Pumpkins             |mystical_pumpkins             |0.3.0               |ENQUEUE_IM|NOSIGNATURE
		allurement-1.16.5-1.2.0.jar                       |Allurement                    |allurement                    |1.2.0               |ENQUEUE_IM|NOSIGNATURE
		sodium-forge-2.9.1+rev.63112e3.jar                |SodiumReforged                |sodium                        |2.9.1+rev.63112e3   |ENQUEUE_IM|NOSIGNATURE
		JustEnoughResources-1.16.5-0.12.1.121.jar         |Just Enough Resources         |jeresources                   |0.12.1.121          |ENQUEUE_IM|NOSIGNATURE
		CraftTweaker-1.16.5-7.1.0.346.jar                 |CraftTweaker                  |crafttweaker                  |7.1.0.346           |ENQUEUE_IM|NOSIGNATURE
		forge-1.16.5-36.1.0-universal.jar                 |Forge                         |forge                         |36.1.0              |ENQUEUE_IM|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		supplementaries-1.16.5-0.14.4d.jar                |Supplementaries               |supplementaries               |1.16.5-0.14.4       |ENQUEUE_IM|NOSIGNATURE
		neapolitan-1.16.5-2.1.0.jar                       |Neapolitan                    |neapolitan                    |2.1.0               |ENQUEUE_IM|NOSIGNATURE
		selene-1.16.5-1.4.jar                             |Selene                        |selene                        |1.4                 |ENQUEUE_IM|NOSIGNATURE
		antiqueatlas-5.4.4-forge.jar                      |Antique Atlas                 |antiqueatlas                  |5.4.4-forge         |ENQUEUE_IM|NOSIGNATURE
		DungeonsArise-1.16.5-2.1.43-alpha.jar             |When Dungeons Arise           |dungeons_arise                |2.1.43              |ENQUEUE_IM|NOSIGNATURE
		forge-1.16.5-36.1.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |ENQUEUE_IM|NOSIGNATURE
		upgrade_aquatic-1.16.5-3.1.0.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.1.0               |ENQUEUE_IM|NOSIGNATURE
		cofh_core-1.16.4-1.2.1.jar                        |CoFH Core                     |cofh_core                     |1.2.1               |ENQUEUE_IM|NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |ENQUEUE_IM|NOSIGNATURE
		FarmersDelight-1.16.5-0.4.5.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.4.5        |ENQUEUE_IM|NOSIGNATURE
		repurposed_structures-1.16.5-2.7.8-forge.jar      |Repurposed Structures         |repurposed_structures         |1.16.5-2.7.8-forge  |ENQUEUE_IM|NOSIGNATURE
		morevillagers-FORGE-1.16.5-1.5.2.jar              |More Villagers                |morevillagers                 |1.5.1               |ENQUEUE_IM|NOSIGNATURE
		theoneprobe-1.16-3.1.4.jar                        |The One Probe                 |theoneprobe                   |1.16-3.1.4          |ENQUEUE_IM|NOSIGNATURE
		Abundance-1.16.5-1.0.5.jar                        |Abundance                     |abundance                     |1.16.5-1.0.5        |ENQUEUE_IM|NOSIGNATURE
		oreganized-1.16.4-0.5.0-beta.jar                  |Oreganized Mod                |oreganized                    |1.16.4-0.5.0-beta   |ENQUEUE_IM|NOSIGNATURE
		archers_paradox-1.16.4-1.2.0.jar                  |Archer's Paradox              |archers_paradox               |1.2.0               |ENQUEUE_IM|NOSIGNATURE
		CavesAndCliffsBackport-1.16.5-5.2.jar             |Caves & Cliffs Backport       |cavesandcliffs                |5.2                 |ENQUEUE_IM|NOSIGNATURE
		DarkerDepths-1.16.5-1.0.1.jar                     |Darker Depths                 |darkerdepths                  |1.0.1}              |ENQUEUE_IM|NOSIGNATURE
		personality-1.16.5-1.0.2.jar                      |Personality                   |personality                   |1.0.2               |ENQUEUE_IM|NOSIGNATURE
		atmospheric-1.16.5-3.1.0.jar                      |Atmospheric                   |atmospheric                   |3.1.0               |ENQUEUE_IM|NOSIGNATURE
		Bountiful-1.16.4-3.3.1.jar                        |Bountiful                     |bountiful                     |1.16.4-3.3.1        |ENQUEUE_IM|NOSIGNATURE
		mostructures-forge-1.2.0-1.16.5.jar               |Mo' Structures                |mostructures                  |1.2.0-1.16.5        |ENQUEUE_IM|NOSIGNATURE
		flywheel-1.16-0.1.0.jar                           |Flywheel                      |flywheel                      |1.16-0.1.0          |ENQUEUE_IM|NOSIGNATURE
		create-mc1.16.5_v0.3.2.jar                        |Create                        |create                        |v0.3.2 for 1.16.5   |ENQUEUE_IM|NOSIGNATURE
		curios-forge-1.16.5-4.0.5.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.2      |ENQUEUE_IM|NOSIGNATURE
		tetra-1.16.5-3.14.1.jar                           |Tetra                         |tetra                         |3.14.1              |ENQUEUE_IM|NOSIGNATURE
		tetranomicon-1.3.jar                              |Tetranomicon                  |tetranomicon                  |1.3                 |ENQUEUE_IM|NOSIGNATURE
		savageandravage-1.16.5-3.1.0.jar                  |Savage & Ravage               |savageandravage               |3.1.0               |ENQUEUE_IM|NOSIGNATURE
		rats-7.2.0-1.16.5.jar                             |Rats                          |rats                          |7.2.0               |ENQUEUE_IM|NOSIGNATURE
		FastWorkbench-1.16.4-4.5.1.jar                    |FastWorkbench                 |fastbench                     |4.5.1               |ENQUEUE_IM|NOSIGNATURE
		autumnity-1.16.5-2.1.1.jar                        |Autumnity                     |autumnity                     |2.1.1               |ENQUEUE_IM|NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |ENQUEUE_IM|NOSIGNATURE
		abnormals_delight-1.16.5-1.1.1.jar                |Abnormals Delight             |abnormals_delight             |1.1.1               |ENQUEUE_IM|NOSIGNATURE
		YungsExtras-Forge-1.16.4-1.0.jar                  |YUNG's Extras                 |yungsextras                   |Forge-1.16.4-1.0    |ENQUEUE_IM|NOSIGNATURE
		tombstone-1.16-6.4.5.jar                          |Corail Tombstone              |tombstone                     |6.4.5               |ENQUEUE_IM|NOSIGNATURE
		Quark-r2.4-314.jar                                |Quark                         |quark                         |r2.4-314            |ENQUEUE_IM|NOSIGNATURE
		Peculiars-1.16.4-1.1.0.jar                        |Peculiars                     |peculiars                     |1.1.0               |ENQUEUE_IM|NOSIGNATURE
		BetterStrongholds-1.16.4-1.1.jar                  |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.1          |ENQUEUE_IM|NOSIGNATURE
		structurize-0.13.199-ALPHA-universal.jar          |Structurize                   |structurize                   |0.13.199-ALPHA      |ENQUEUE_IM|NOSIGNATURE
		minecolonies-0.14.279-ALPHA-universal.jar         |MineColonies                  |minecolonies                  |0.14.279-ALPHA      |ENQUEUE_IM|NOSIGNATURE
		FastFurnace-1.16.4-4.4.0.jar                      |FastFurnace                   |fastfurnace                   |4.4.0               |ENQUEUE_IM|NOSIGNATURE
		sapience-1.16.5-1.1.2.jar                         |Sapience                      |sapience                      |1.1.2               |ENQUEUE_IM|NOSIGNATURE
		cobbler-1.6.1.jar                                 |Shulkers Faithful Factories   |cobbler                       |1.6.1               |ENQUEUE_IM|NOSIGNATURE
		appleskin-forge-mc1.16.x-2.0.0.jar                |AppleSkin                     |appleskin                     |mc1.16.4-2.0.0      |ENQUEUE_IM|NOSIGNATURE
		ferritecore-2.0.4-forge.jar                       |Ferrite Core                  |ferritecore                   |2.0.4               |ENQUEUE_IM|41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		curiouselytra-forge-1.16.5-4.0.2.3.jar            |Curious Elytra                |curiouselytra                 |1.16.5-4.0.2.3      |ENQUEUE_IM|NOSIGNATURE
		AI-Improvements-1.16.2-0.3.0.jar                  |AI-Improvements               |aiimprovements                |0.3.0               |ENQUEUE_IM|NOSIGNATURE
		Germinate V.1.1.3a.jar                            |Germinate                     |plantae_kingdom               |Stable              |ENQUEUE_IM|NOSIGNATURE
		bgcore-1.16.5-3.2.jar                             |bgcore                        |bgcore                        |3.2                 |ENQUEUE_IM|NOSIGNATURE
		Orcinus-Caves-1.0.0.jar                           |Orcinus's Cavern              |cavern                        |1.0-SNAPSHOT        |ENQUEUE_IM|NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |ENQUEUE_IM|NOSIGNATURE
		expandability-2.0.1-forge.jar                     |ExpandAbility                 |expandability                 |2.0.1               |ENQUEUE_IM|NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |ENQUEUE_IM|NOSIGNATURE
		geckolib-forge-1.16.5-3.0.41.jar                  |GeckoLib                      |geckolib3                     |3.0.41              |ENQUEUE_IM|NOSIGNATURE
		OpenLoader-1.16.5-9.0.3.jar                       |OpenLoader                    |openloader                    |9.0.3               |ENQUEUE_IM|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
	Crash Report UUID: 4d5f7030-e8d0-4f1c-9fad-b630c524d28b
	Launched Version: forge-36.1.0
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: NVIDIA GeForce GT 650M OpenGL Engine GL version 2.1 NVIDIA-12.0.24 355.11.10.50.10.103, NVIDIA Corporation
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz

**Comment by Jozufozu** [comment]
Could you upload your `latest.log` to [pastebin](https://pastebin.com/)?

**Comment by StrangerSon71** [comment]
[How do I do a link?]((https://pastebin.com/Z8aLSf5d))

**Comment by Dunkmania101** [comment]
Links in Markdown use the following syntax:
`[name](https://example.com)`
[name](https://example.com)


Also, I got what I suspect is the same crash, so I'll link my log here:
[latest.log](https://gist.github.com/Dunkmania101/b4091c1cac685d2f98d57d9c810839b0)

At least in my case, it seems to be something to do with the version of GLSL and a shader called 'create:area_effect.vert'.
