### ISSUE TITLE
crash when loading map chunks in JourneyMap for 1.18

### ISSUE THREAD

**Issue by jambox5** [Engine-Room/Flywheel#57]
-created new world in 1.18.0 (with Flywheel & Create in mods)
-open Journey Maap
-select 'autoMap'
-crash due to Flywheel

**Comment by jambox5** [comment]
additionally crashes when game is paused via esc button. Appears to be issue with partial ticks in Flywheel:

Description: Unexpected error

org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: Illegal classload request for com.jozufozu.flywheel.mixin.PausedPartialTickAccessor. Mixin is defined in flywheel.mixins.json and cannot be referenced directly
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:334) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-9.0.7.jar:9.0.7+91+master.8569cdf] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.0.7.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.0.7.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.0.7.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130) ~[securejarhandler-0.9.54.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at com.jozufozu.flywheel.util.AnimationTickHolder.getPartialTicks(AnimationTickHolder.java:40) ~[flywheel-forge-1.18-0.4.0.jar%2362!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.util.AnimationTickHolder.getRenderTime(AnimationTickHolder.java:35) ~[flywheel-forge-1.18-0.4.0.jar%2362!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.core.shader.WorldProgram.bind(WorldProgram.java:72) ~[flywheel-forge-1.18-0.4.0.jar%2362!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancedMaterialRenderer.render(InstancedMaterialRenderer.java:36) ~[flywheel-forge-1.18-0.4.0.jar%2362!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancedMaterialGroup.render(InstancedMaterialGroup.java:52) ~[flywheel-forge-1.18-0.4.0.jar%2362!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancingEngine.lambda$render$1(InstancingEngine.java:100) ~[flywheel-forge-1.18-0.4.0.jar%2362!:1.18-0.4.0] {re:classloading}
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancingEngine.render(InstancingEngine.java:100) ~[flywheel-forge-1.18-0.4.0.jar%2362!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstanceWorld.renderLayer(InstanceWorld.java:101) ~[flywheel-forge-1.18-0.4.0.jar%2362!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstancedRenderDispatcher.renderLayer(InstancedRenderDispatcher.java:83) ~[flywheel-forge-1.18-0.4.0.jar%2362!:1.18-0.4.0] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_36_InstancedRenderDispatcher_renderLayer_RenderLayerEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraft.client.renderer.LevelRenderer.handler$zzn000$renderLayer(LevelRenderer.java:5067) ~[client-1.18-20211130.085255-srg.jar%2380!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_172993_(LevelRenderer.java:1550) ~[client-1.18-20211130.085255-srg.jar%2380!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1174) ~[client-1.18-20211130.085255-srg.jar%2380!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1050) ~[client-1.18-20211130.085255-srg.jar%2380!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:830) ~[client-1.18-20211130.085255-srg.jar%2380!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1040) ~[client-1.18-20211130.085255-srg.jar%2380!:?] {re:mixin,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#createLevel,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#createLevel,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#createLevel,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18-20211130.085255-srg.jar%2380!:?] {re:mixin,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#createLevel,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#createLevel,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#createLevel,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18-20211130.085255-srg.jar%2380!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18-38.0.17.jar%2323!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:334) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-9.0.7.jar:9.0.7+91+master.8569cdf] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.0.7.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.0.7.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.0.7.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130) ~[securejarhandler-0.9.54.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at com.jozufozu.flywheel.util.AnimationTickHolder.getPartialTicks(AnimationTickHolder.java:40) ~[flywheel-forge-1.18-0.4.0.jar%2362!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.util.AnimationTickHolder.getRenderTime(AnimationTickHolder.java:35) ~[flywheel-forge-1.18-0.4.0.jar%2362!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.core.shader.WorldProgram.bind(WorldProgram.java:72) ~[flywheel-forge-1.18-0.4.0.jar%2362!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancedMaterialRenderer.render(InstancedMaterialRenderer.java:36) ~[flywheel-forge-1.18-0.4.0.jar%2362!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancedMaterialGroup.render(InstancedMaterialGroup.java:52) ~[flywheel-forge-1.18-0.4.0.jar%2362!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancingEngine.lambda$render$1(InstancingEngine.java:100) ~[flywheel-forge-1.18-0.4.0.jar%2362!:1.18-0.4.0] {re:classloading}
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancingEngine.render(InstancingEngine.java:100) ~[flywheel-forge-1.18-0.4.0.jar%2362!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstanceWorld.renderLayer(InstanceWorld.java:101) ~[flywheel-forge-1.18-0.4.0.jar%2362!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstancedRenderDispatcher.renderLayer(InstancedRenderDispatcher.java:83) ~[flywheel-forge-1.18-0.4.0.jar%2362!:1.18-0.4.0] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_36_InstancedRenderDispatcher_renderLayer_RenderLayerEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraft.client.renderer.LevelRenderer.handler$zzn000$renderLayer(LevelRenderer.java:5067) ~[client-1.18-20211130.085255-srg.jar%2380!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_172993_(LevelRenderer.java:1550) ~[client-1.18-20211130.085255-srg.jar%2380!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1174) ~[client-1.18-20211130.085255-srg.jar%2380!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1050) ~[client-1.18-20211130.085255-srg.jar%2380!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}

**Comment by Jozufozu** [comment]
Moving discussion for this to #69
