### ISSUE TITLE
game crashing on open, Mac

### ISSUE THREAD

**Issue by GreenPanda64** [Engine-Room/Flywheel#65]
### Describe the Bug

When launching a single-player or multiplayer world, right before its supposed to open, (after the loading screen) the entire game crashes and sends me back to the launcher, crashing the game. Regardless of what kind of world. I have the latest forge, flywheel and create mod

### Reproduction Steps

1. have forge 1.18, flywheel, and the create mod downloaded
2. launch the game in forge 1.18
2. join a world (either multiplayer or single)
3. watch the game crash after the loading terrain screen

### Expected Result

Launch game
click world
Not have it crash

### Screenshots and Videos

<img width="988" alt="Screen Shot 2021-12-11 at 9 10 48 PM" src="https://user-images.githubusercontent.com/95976732/145697780-698d6a6d-d0b5-47ba-80e4-cd74995930b2.png">
`

### Operating System

macOS Monterey Version 12.0.1

### Mod Version

0.4.0

### Minecraft Version

1.18

### Forge Version

1.18

### Other Mods

Create mod

### Additional Context

Time: 12/11/21, 9:10 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?] {re:mixin}
	at org.lwjgl.system.MemoryUtil.memAddress(MemoryUtil.java:718) ~[lwjgl-3.2.1.jar%2344!:build 12] {re:mixin}
	at com.jozufozu.flywheel.backend.struct.UnsafeBufferWriter.acquireWritePointer(UnsafeBufferWriter.java:43) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.struct.UnsafeBufferWriter.<init>(UnsafeBufferWriter.java:26) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.core.materials.model.writer.UnsafeModelWriter.<init>(UnsafeModelWriter.java:14) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.core.materials.model.ModelType.getWriter(ModelType.java:30) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.instancing.GPUInstancer.realloc(GPUInstancer.java:184) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.instancing.GPUInstancer.renderSetup(GPUInstancer.java:116) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.instancing.GPUInstancer.render(GPUInstancer.java:53) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancedMaterialRenderer.render(InstancedMaterialRenderer.java:42) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancedMaterialGroup.render(InstancedMaterialGroup.java:52) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancingEngine.lambda$render$1(InstancingEngine.java:100) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancingEngine.render(InstancingEngine.java:100) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstanceWorld.renderLayer(InstanceWorld.java:101) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstancedRenderDispatcher.renderLayer(InstancedRenderDispatcher.java:83) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_12_InstancedRenderDispatcher_renderLayer_RenderLayerEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraft.client.renderer.LevelRenderer.handler$zzf000$renderLayer(LevelRenderer.java:4567) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:CancelEntityRenderMixin,pl:mixin:APP:flywheel.mixins.json:FixFabulousDepthMixin,pl:mixin:APP:flywheel.mixins.json:LevelRendererAccessor,pl:mixin:APP:flywheel.mixins.json:RenderHooksMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_172993_(LevelRenderer.java:1550) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:CancelEntityRenderMixin,pl:mixin:APP:flywheel.mixins.json:FixFabulousDepthMixin,pl:mixin:APP:flywheel.mixins.json:LevelRendererAccessor,pl:mixin:APP:flywheel.mixins.json:RenderHooksMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1174) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:CancelEntityRenderMixin,pl:mixin:APP:flywheel.mixins.json:FixFabulousDepthMixin,pl:mixin:APP:flywheel.mixins.json:LevelRendererAccessor,pl:mixin:APP:flywheel.mixins.json:RenderHooksMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1050) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:830) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1040) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18-38.0.15.jar%2322!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?] {re:mixin}
	at org.lwjgl.system.MemoryUtil.memAddress(MemoryUtil.java:718) ~[lwjgl-3.2.1.jar%2344!:build 12] {re:mixin}
	at com.jozufozu.flywheel.backend.struct.UnsafeBufferWriter.acquireWritePointer(UnsafeBufferWriter.java:43) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.struct.UnsafeBufferWriter.<init>(UnsafeBufferWriter.java:26) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.core.materials.model.writer.UnsafeModelWriter.<init>(UnsafeModelWriter.java:14) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.core.materials.model.ModelType.getWriter(ModelType.java:30) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.instancing.GPUInstancer.realloc(GPUInstancer.java:184) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.instancing.GPUInstancer.renderSetup(GPUInstancer.java:116) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.instancing.GPUInstancer.render(GPUInstancer.java:53) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancedMaterialRenderer.render(InstancedMaterialRenderer.java:42) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancedMaterialGroup.render(InstancedMaterialGroup.java:52) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancingEngine.lambda$render$1(InstancingEngine.java:100) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancingEngine.render(InstancingEngine.java:100) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstanceWorld.renderLayer(InstanceWorld.java:101) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstancedRenderDispatcher.renderLayer(InstancedRenderDispatcher.java:83) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_12_InstancedRenderDispatcher_renderLayer_RenderLayerEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraft.client.renderer.LevelRenderer.handler$zzf000$renderLayer(LevelRenderer.java:4567) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:CancelEntityRenderMixin,pl:mixin:APP:flywheel.mixins.json:FixFabulousDepthMixin,pl:mixin:APP:flywheel.mixins.json:LevelRendererAccessor,pl:mixin:APP:flywheel.mixins.json:RenderHooksMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_172993_(LevelRenderer.java:1550) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:CancelEntityRenderMixin,pl:mixin:APP:flywheel.mixins.json:FixFabulousDepthMixin,pl:mixin:APP:flywheel.mixins.json:LevelRendererAccessor,pl:mixin:APP:flywheel.mixins.json:RenderHooksMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1174) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:CancelEntityRenderMixin,pl:mixin:APP:flywheel.mixins.json:FixFabulousDepthMixin,pl:mixin:APP:flywheel.mixins.json:LevelRendererAccessor,pl:mixin:APP:flywheel.mixins.json:RenderHooksMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1050) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Ada_Lugume'/11420, l='ClientLevel', x=-66.05, y=-54.00, z=-59.84]]
	Chunk stats: 2209, 747
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,107,32), Section: (at 0,11,0 in 0,6,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 7473862 game time, 584119 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:407) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:create.mixins.json:DestroyProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2249) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:682) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18-38.0.15.jar%2322!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Mod Resources, Default

-- System Details --
Details:
	Minecraft Version: 1.18
	Minecraft Version ID: 1.18
	Operating System: Mac OS X (x86_64) version 12.0.1
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 902248280 bytes (860 MiB) / 1979711488 bytes (1888 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 1.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel Iris Plus Graphics 645
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 1536.00
	Graphics card #0 deviceId: 0x3ea6
	Graphics card #0 versionInfo: Revision ID: 0x0001
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: LPDDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: LPDDR3
	Virtual memory max (MB): 10240.00
	Virtual memory used (MB): 7288.30
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 1263.50
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.18-forge-38.0.15
	Backend library: LWJGL version 3.2.1 SNAPSHOT
	Backend API: Intel(R) Iris(TM) Plus Graphics 645 GL version 4.1 INTEL-18.2.10, Intel Inc.
	Window size: 1708x960
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (United Kingdom)
	CPU: 8x Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18-20211130.085255-srg.jar               |Minecraft                     |minecraft                     |1.18                |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.18-38.0.15-universal.jar                  |Forge                         |forge                         |38.0.15             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		flywheel-forge-1.18-0.4.0.jar                     |Flywheel                      |flywheel                      |1.18-0.4.0          |DONE      |Manifest: NOSIGNATURE
		create-mc1.18_v0.4.jar                            |Create                        |create                        |0.4                 |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: ca7eb1fb-b4e6-4f68-a794-840bb5e9f4ae
	FML: 38.0
	Forge: net.minecraftforge:38.0.15

**Comment by Grzegorz1337** [comment]
I think this is exactly same as #53, also there are linked other crush logs

**Comment by StrangeThistle** [comment]
I have the same issue. Disabling the engine in the Flywheel config file will at least let me load a world.

**Comment by lucsoft** [comment]
i have the same crashes testing it on macOS

here are every crash i had testing the mod. 
[Archiv.zip](https://github.com/Jozufozu/Flywheel/files/7700028/Archiv.zip)

If you need support debugging this issue im here to help!

**Comment by lucsoft** [comment]
Notice if i disable flywheel everything works and blocks render perfectly

so this could be a current workaround

**Comment by GreenPanda64** [comment]
> I have the same issue. Disabling the engine in the Flywheel config file will at least let me load a world.

would you possibly know how that is done because I don't

**Comment by lucsoft** [comment]
> > I have the same issue. Disabling the engine in the Flywheel config file will at least let me load a world.
> 
> 
> 
> would you possibly know how that is done because I don't
> 
> 

Launch Minecraft. Go to the create settings then other mod options then flywheel and then just enable to false

This should be the way. (This is how I remember it)

**Comment by GreenPanda64** [comment]
> > > I have the same issue. Disabling the engine in the Flywheel config file will at least let me load a world.
> > 
> > 
> > would you possibly know how that is done because I don't
> 
> Launch Minecraft. Go to the create settings then other mod options then flywheel and then just enable to false
> 
> This should be the way. (This is how I remember it)

thank you I know owe you my first born

**Comment by ghost** [comment]
Use 0.4.1 version
[![oXzOaV.png](https://s4.ax1x.com/2021/12/13/oXzOaV.png)](https://imgtu.com/i/oXzOaV)

**Comment by lucsoft** [comment]
Can confirm everything is working, i tested it on Intel GPU and Nvidia GPU and it works fine

@GreenPanda64 can you update your mods and activate Flywheel again? and check? i think we can close this issue when it works on your side too!

**Comment by Jozufozu** [comment]
Fixed in [0.4.1](https://www.curseforge.com/minecraft/mc-mods/flywheel/files/3564677)
