### ISSUE TITLE
1.17 crash client side. Please, Help is needed.

### ISSUE THREAD

**Issue by Buyasta101** [Engine-Room/Flywheel#70]
### Describe the Bug

experiencing crashing when using mech bearing or any modded block that moves a block. removed all mods still experiencing same result. Attaching crash report, any and all help on this matter is welcomed.

Thanks, Buyasta.

---- Minecraft Crash Report ----
// There are four lights!

Time: 12/14/21, 4:24 PM
Description: Unexpected error

com.jozufozu.flywheel.backend.gl.error.GlException: mapBufferRange(ARRAY_BUFFER, 0, 1472, 2)
	at com.jozufozu.flywheel.backend.gl.buffer.MappedBufferRange.checkAndMap(MappedBufferRange.java:36) ~[flywheel-forge-1.17-0.3.0.jar%2354!:1.17-0.3.0] {re:classloading}
	at com.jozufozu.flywheel.backend.gl.buffer.MappedBuffer.position(MappedBuffer.java:69) ~[flywheel-forge-1.17-0.3.0.jar%2354!:1.17-0.3.0] {re:classloading}
	at com.jozufozu.flywheel.backend.gl.buffer.MappedBufferRange.position(MappedBufferRange.java:25) ~[flywheel-forge-1.17-0.3.0.jar%2354!:1.17-0.3.0] {re:classloading}
	at com.jozufozu.flywheel.backend.model.ModelPool.uploadPending(ModelPool.java:137) ~[flywheel-forge-1.17-0.3.0.jar%2354!:1.17-0.3.0] {re:classloading}
	at com.jozufozu.flywheel.backend.model.ModelPool.flush(ModelPool.java:70) ~[flywheel-forge-1.17-0.3.0.jar%2354!:1.17-0.3.0] {re:classloading}
	at com.jozufozu.flywheel.backend.material.MaterialRenderer.render(MaterialRenderer.java:33) ~[flywheel-forge-1.17-0.3.0.jar%2354!:1.17-0.3.0] {re:classloading}
	at com.jozufozu.flywheel.backend.material.MaterialGroupImpl.render(MaterialGroupImpl.java:48) ~[flywheel-forge-1.17-0.3.0.jar%2354!:1.17-0.3.0] {re:classloading}
	at com.jozufozu.flywheel.backend.material.MaterialManagerImpl.render(MaterialManagerImpl.java:92) ~[flywheel-forge-1.17-0.3.0.jar%2354!:1.17-0.3.0] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraptionManager.renderLayer(FlwContraptionManager.java:62) ~[create-mc1.17.1_v0.4.jar%2353!:mc1.17.1_v0.4] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderDispatcher.renderLayer(ContraptionRenderDispatcher.java:72) ~[create-mc1.17.1_v0.4.jar%2353!:mc1.17.1_v0.4] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_112_ContraptionRenderDispatcher_renderLayer_RenderLayerEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraft.client.renderer.LevelRenderer.handler$zzg000$renderLayer(LevelRenderer.java:4396) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_172993_(LevelRenderer.java:1396) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1020) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1050) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:830) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1039) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:659) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.1.1.jar%2323!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.jozufozu.flywheel.backend.gl.buffer.MappedBufferRange.checkAndMap(MappedBufferRange.java:36) ~[flywheel-forge-1.17-0.3.0.jar%2354!:1.17-0.3.0] {re:classloading}
	at com.jozufozu.flywheel.backend.gl.buffer.MappedBuffer.position(MappedBuffer.java:69) ~[flywheel-forge-1.17-0.3.0.jar%2354!:1.17-0.3.0] {re:classloading}
	at com.jozufozu.flywheel.backend.gl.buffer.MappedBufferRange.position(MappedBufferRange.java:25) ~[flywheel-forge-1.17-0.3.0.jar%2354!:1.17-0.3.0] {re:classloading}
	at com.jozufozu.flywheel.backend.model.ModelPool.uploadPending(ModelPool.java:137) ~[flywheel-forge-1.17-0.3.0.jar%2354!:1.17-0.3.0] {re:classloading}
	at com.jozufozu.flywheel.backend.model.ModelPool.flush(ModelPool.java:70) ~[flywheel-forge-1.17-0.3.0.jar%2354!:1.17-0.3.0] {re:classloading}
	at com.jozufozu.flywheel.backend.material.MaterialRenderer.render(MaterialRenderer.java:33) ~[flywheel-forge-1.17-0.3.0.jar%2354!:1.17-0.3.0] {re:classloading}
	at com.jozufozu.flywheel.backend.material.MaterialGroupImpl.render(MaterialGroupImpl.java:48) ~[flywheel-forge-1.17-0.3.0.jar%2354!:1.17-0.3.0] {re:classloading}
	at com.jozufozu.flywheel.backend.material.MaterialManagerImpl.render(MaterialManagerImpl.java:92) ~[flywheel-forge-1.17-0.3.0.jar%2354!:1.17-0.3.0] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraptionManager.renderLayer(FlwContraptionManager.java:62) ~[create-mc1.17.1_v0.4.jar%2353!:mc1.17.1_v0.4] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderDispatcher.renderLayer(ContraptionRenderDispatcher.java:72) ~[create-mc1.17.1_v0.4.jar%2353!:mc1.17.1_v0.4] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_112_ContraptionRenderDispatcher_renderLayer_RenderLayerEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraft.client.renderer.LevelRenderer.handler$zzg000$renderLayer(LevelRenderer.java:4396) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_172993_(LevelRenderer.java:1396) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1020) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1050) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['------------'/2, l='ClientLevel', x=2.99, y=56.00, z=10.99]]
	Chunk stats: 1681, 1225
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,56,8), Section: (at 8,8,8 in 0,3,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 4142 game time, 4142 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:364) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:create.mixins.json:DestroyProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2245) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:681) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.1.1.jar%2323!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Mod Resources, Default

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2049362280 bytes (1954 MiB) / 5771362304 bytes (5504 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f10
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9649
	Graphics card #1 name: Intel(R) UHD Graphics 630
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x3e9b
	Graphics card #1 versionInfo: DriverVersion=27.20.100.9415
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37485.19
	Virtual memory used (MB): 15100.17
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 3.04
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.17.1-forge-37.1.1
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: Intel(R) UHD Graphics 630 GL version 3.2.0 - Build 27.20.100.9415, Intel
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error' x 5
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: mod_resources, vanilla
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	Player Count: 1 / 8; [ServerPlayer[------------------'/2, l='ServerLevel[New World]', x=2.99, y=56.00, z=10.99]]
	Data Packs: vanilla, mod:forge, mod:flywheel, mod:create
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 capability_inject_definalize PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.17.1-20210706.113038-srg.jar             |Minecraft                     |minecraft                     |1.17.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.17.1-37.1.1-universal.jar                 |Forge                         |forge                         |37.1.1              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		flywheel-forge-1.17-0.3.0.jar                     |Flywheel                      |flywheel                      |1.17-0.3.0          |DONE      |Manifest: NOSIGNATURE
		create-mc1.17.1_v0.4.jar                          |Create                        |create                        |0.4                 |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: b0c9b9b5-6828-4dd2-b5bf-cd79f4cf174d
	FML: 37.1
	Forge: net.minecraftforge:37.1.1

### Reproduction Steps

1.
2.
3.
... Attaching any Create block to a rotating bearing causes block to disappear but block collision remains. Any vanilla block attached to bearing crashes the moment it rotates.

### Expected Result

Crash....

### Operating System

windows 10

### What is your GPU?

NVIDIA GeForce RTX 2070

### Mod Version

0.3.0

### Minecraft Version

1.17.1

### Forge Version

37.1.1

### Other Mods

no other mods loaded

### Additional Context

Again any and all help is welcome. 
Thanks

**Comment by Buyasta101** [comment]
Could I Please get some support on this. A new development is that my brother and I have started a server. and the problem is still there. however, all mods he received from my mod folder. so it must be client side.  
If anyone could give me a lead on where to start I would be forever grateful
[crash-2021-12-27_23.50.38-client.txt](https://github.com/Jozufozu/Flywheel/files/7782923/crash-2021-12-27_23.50.38-client.txt)
.

**Comment by Buyasta101** [comment]
![2021-12-28_00 47 11](https://user-images.githubusercontent.com/96148686/147532504-19f59e2d-9002-4e54-9031-ad7afacd4341.png)
![2021-12-28_00 47 08](https://user-images.githubusercontent.com/96148686/147532518-d3e806cd-1a93-467c-83cb-26e3369efeb5.png)

**Comment by Buyasta101** [comment]
fresh install of everything, bearing works can attach blocks, but once rotation begins all attached blocked become invisible. however the collision remains.

**Comment by Buyasta101** [comment]
https://youtu.be/6s24DSoBG1A

**Comment by Buyasta101** [comment]
link is for video showing error.

**Comment by Buyasta101** [comment]
Issues resolved, downgraded to supported version. 1.16.5
